### ISSUE TITLE
When i bot any stream i get this error please help

### ISSUE THREAD

**Issue by ashdc125** [KevinLage/YouTube-Livestream-Botter#14]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "site-packages\urllib3\connection.py", line 160, in _new_conn
  File "site-packages\urllib3\util\connection.py", line 80, in create_connection
  File "site-packages\urllib3\util\connection.py", line 70, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 603, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 344, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
  File "site-packages\urllib3\connection.py", line 316, in connect
  File "site-packages\urllib3\connection.py", line 169, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001F7B0F23A48>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 641, in urlopen
  File "site-packages\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.proxyscrape.com', port=443): Max retries exceeded with url: /?request=getproxies&proxytype=http&timeout=10000&ssl=yes (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001F7B0F23A48>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

**Comment by KevinLage** [comment]
are you using the .exe?
