### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by rrockyrraccoon** [KevinLage/YouTube-Livestream-Botter#142]
after entering Id and pressing enter i get back the flowing.  someone please help me.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 597, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 343, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
  File "site-packages\urllib3\connection.py", line 337, in connect
  File "site-packages\urllib3\util\ssl_.py", line 347, in ssl_wrap_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 439, in send
  File "site-packages\urllib3\connectionpool.py", line 637, in urlopen
  File "site-packages\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.proxyscrape.com', port=443): Max retries exceeded with url: /?request=getproxies&proxytype=http&timeout=10000&ssl=yes (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "yes.py", line 72, in update
  File "site-packages\requests\api.py", line 76, in get
  File "site-packages\requests\api.py", line 61, in request
  File "site-packages\requests\sessions.py", line 530, in request
  File "site-packages\requests\sessions.py", line 643, in send
  File "site-packages\requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.proxyscrape.com', port=443): Max retries exceeded with url: /?request=getproxies&proxytype=http&timeout=10000&ssl=yes (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)')))

**Comment by KevinLage** [comment]
looks like an proxyscrape issue, can u access proxyscrape.com and api.proxyscrape.com in your browser?
