### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by BGP19000** [KevinLage/YouTube-Livestream-Botter#5]
I received this message after entering the ID

ID?
SBdkOH2j6oQ
Exception in thread Thread-1:
Traceback (most recent call last):
  File "requests\packages\urllib3\connectionpool.py", line 544, in urlopen
  File "requests\packages\urllib3\connectionpool.py", line 341, in _make_request
  File "requests\packages\urllib3\connectionpool.py", line 761, in _validate_conn
  File "requests\packages\urllib3\connection.py", line 238, in connect
  File "requests\packages\urllib3\util\ssl_.py", line 279, in ssl_wrap_socket
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 370, in send
  File "requests\packages\urllib3\connectionpool.py", line 574, in urlopen
requests.packages.urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "main1.py", line 60, in update
  File "requests\api.py", line 69, in get
  File "requests\api.py", line 50, in request
  File "requests\sessions.py", line 465, in request
  File "requests\sessions.py", line 573, in send
  File "requests\adapters.py", line 431, in send
requests.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1076)

![image](https://user-images.githubusercontent.com/39221078/67151310-45c7b480-f2bc-11e9-99e6-bad2d4b7a408.png)

**Comment by KevinLage** [comment]
.exe or .py?

**Comment by BGP19000** [comment]
Both

**Comment by KevinLage** [comment]
which OS?

**Comment by BGP19000** [comment]
Windows 10

**Comment by TheyLoveJay** [comment]
I'm kinda new how do i open it lol
