### ISSUE TITLE
I am not able to get it working!

### ISSUE THREAD

**Issue by Hoffao77** [KevinLage/YouTube-Livestream-Botter#60]
This is what i get when i run the bot, it is the exe.
Is there a fix for this?

__________________________________________________________________________________________________

███████╗████████╗██████╗ ███████╗ █████╗ ███╗   ███╗      ██████╗  ██████╗ ████████╗████████╗███████╗██████╗
██╔════╝╚══██╔══╝██╔══██╗██╔════╝██╔══██╗████╗ ████║      ██╔══██╗██╔═══██╗╚══██╔══╝╚══██╔══╝██╔════╝██╔══██╗
███████╗   ██║   ██████╔╝█████╗  ███████║██╔████╔██║█████╗██████╔╝██║   ██║   ██║      ██║   █████╗  ██████╔╝
╚════██║   ██║   ██╔══██╗██╔══╝  ██╔══██║██║╚██╔╝██║╚════╝██╔══██╗██║   ██║   ██║      ██║   ██╔══╝  ██╔══██╗
███████║   ██║   ██║  ██║███████╗██║  ██║██║ ╚═╝ ██║      ██████╔╝╚██████╔╝   ██║      ██║   ███████╗██║  ██║
╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝      ╚═════╝  ╚═════╝    ╚═╝      ╚═╝   ╚══════╝╚═╝  ╚═╝

ID?
oKI5NrjEuTc
Exception in thread Thread-1:
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 597, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 343, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
  File "site-packages\urllib3\connection.py", line 337, in connect
  File "site-packages\urllib3\util\ssl_.py", line 347, in ssl_wrap_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLError: [SSL] unknown error (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 439, in send
  File "site-packages\urllib3\connectionpool.py", line 637, in urlopen
  File "site-packages\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.proxyscrape.com', port=443): Max retries exceeded with url: /?request=getproxies&proxytype=http&timeout=10000&ssl=yes (Caused by SSLError(SSLError(1, '[SSL] unknown error (_ssl.c:1108)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "bot.py", line 62, in update
  File "site-packages\requests\api.py", line 75, in get
  File "site-packages\requests\api.py", line 60, in request
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.proxyscrape.com', port=443): Max retries exceeded with url: /?request=getproxies&proxytype=http&timeout=10000&ssl=yes (Caused by SSLError(SSLError(1, '[SSL] unknown error (_ssl.c:1108)')))
How many Threads? Recommended: 500 - 1000

**Comment by KevinLage** [comment]
the bot cant connect to proxyscrape.com

do you have any proxys or debuggers on windows running?

**Comment by Hoffao77** [comment]
Not that i now its a freshly installed Windows Server 2019.
Should i disable Windows Defender maybe it has some kind of debuggers or proxys?

**Comment by KevinLage** [comment]
try to access proxyscrape.com in your browser
