### ISSUE TITLE
Stuck at 0

### ISSUE THREAD

**Issue by Gijj** [KevinLage/YouTube-Livestream-Botter#64]
Error code:Exception in thread Thread-1:
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 597, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 343, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
  File "site-packages\urllib3\connection.py", line 337, in connect
  File "site-packages\urllib3\util\ssl_.py", line 347, in ssl_wrap_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLError: [SSL] unknown error (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 439, in send
  File "site-packages\urllib3\connectionpool.py", line 637, in urlopen
  File "site-packages\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.proxyscrape.com', port=443): Max retries exceeded with url: /?request=getproxies&proxytype=http&timeout=10000&ssl=yes (Caused by SSLError(SSLError(1, '[SSL] unknown error (_ssl.c:1108)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "bot.py", line 62, in update
  File "site-packages\requests\api.py", line 75, in get
  File "site-packages\requests\api.py", line 60, in request
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.proxyscrape.com', port=443): Max retries exceeded with url: /?request=getproxies&proxytype=http&timeout=10000&ssl=yes (Caused by SSLError(SSLError(1, '[SSL] unknown error (_ssl.c:1108)')))

It then asks for threads and gets stuck at 0 botted

**Comment by KevinLage** [comment]
looks like you cant access proxyscrape.com

does the website load in your browser (proxyscrape.com)?

**Comment by Gijj** [comment]
It's blocked should I use a vpn

**Comment by KevinLage** [comment]
then turn your vpn off
